version: "2"
run:
  modules-download-mode: readonly
linters:
  enable:
    - copyloopvar
    - depguard
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - importas
    - misspell
    - nolintlint
    - prealloc
    - revive
    - testifylint
    - unconvert
    - unparam
    - usestdlibvars
    - whitespace
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/docker/docker
              desc: https://github.com/ustclug/Yuki/issues/44
    exhaustive:
      explicit-exhaustive-switch: true
    govet:
      enable:
        - nilness
    revive:
      confidence: 0.6
      rules:
        - name: blank-imports
        - name: dot-imports
        - name: error-strings
        - name: errorf
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/ustclug/Yuki)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
