version: 2
before:
  hooks:
    - go mod tidy
builds:
  - id: yukid
    binary: yukid
    env:
      - CGO_ENABLED=0
    main: ./cmd/yukid
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/ustclug/Yuki/pkg/info.Version={{.Version}} -X github.com/ustclug/Yuki/pkg/info.BuildDate={{.Date}} -X github.com/ustclug/Yuki/pkg/info.GitCommit={{.Commit}}
  - id: yukictl
    binary: yukictl
    env:
      - CGO_ENABLED=0
    main: ./cmd/yukictl
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/ustclug/Yuki/pkg/info.Version={{.Version}} -X github.com/ustclug/Yuki/pkg/info.BuildDate={{.Date}} -X github.com/ustclug/Yuki/pkg/info.GitCommit={{.Commit}}
    hooks:
      post:
        - cmd: sh -c "{{ .Path }} completion bash > bash_completion"
          dir: "{{ dir (dir .Path) }}"
          output: true
archives:
  - format: binary
    name_template: "{{ .Binary }}_{{ .Os  }}_{{ .Arch }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  use: github-native
nfpms:
  - id: default
    package_name: yuki
    homepage: https://github.com/ustclug/Yuki
    maintainer: "USTC LUG <lug@ustc.edu.cn>"
    description: |-
      USTC Mirror Manager
    formats:
      - deb
    umask: 0o022
    dependencies:
      - "docker.io | docker-engine | docker-ce"
    section: admin
    priority: extra
    provides:
      - yukid
      - yukictl
    scripts:
      postinstall: etc/postinst.sh
      preremove: etc/prerm.sh
    contents:
      - src: dist/bash_completion
        dst: /etc/bash_completion.d/yukictl
      - src: etc/daemon.example.toml
        dst: /etc/yuki/
      - src: etc/yukid.service
        dst: /lib/systemd/system/
      - src: yukictl
        dst: /usr/bin/yuki
        type: symlink

# modelines, feel free to remove those if you don't want/use them:
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
