#debug = true

# Path to sqlite3 db
db_url = "/tmp/yukid.db"

#db_name = "mirror"

# available values:
#   "zfs"
#   "xfs"
#   "default"
fs = "default"

repo_config_dir = "/path/to/config-dir"

# unix local socket: unix:///var/run/docker.sock
# tcp: tcp://127.0.0.1:2375
#docker_endpoint = "unix:///var/run/docker.sock"

# uid:gid
#owner = "1000:1000"

#log_dir = "/var/log/yuki/"

#log_level = "info"

#listen_addr = "127.0.0.1:9999"

#bind_ip = "1.2.3.4"

#name_prefix = "syncing-"

#post_sync = ["/path/to/the/program"]

#images_upgrade_interval = "@every 1h"

#sync_timeout = "48h"

#seccomp_profile = "/path/to/seccomp/profile.json"
