name: Presubmit Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master
    paths:
      - '**.go'

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}

jobs:
  lint:
    runs-on: ubuntu-latest
    # skip for now
    if: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          check-latest: true
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.0
          skip-build-cache: true
          skip-pkg-cache: true

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:3
        ports:
          - 27017:27017

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: stable
        check-latest: true
    - name: Test
      run: |
        docker pull ustcmirror/test
        ci/script.sh
